#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

# if [ -z `which yarn` ]; then
#   echo "yarn is not installed or not in your PATH!\nYou should install yarn or add it's path to your ~/.huskyrc"
#   exit 1
# fi
npx lint-staged